// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SecurityController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ChangeUserNameForm = "_ChangeUserNameForm";
                public readonly string _ConfirmEmailWizardSteps = "_ConfirmEmailWizardSteps";
                public readonly string _SendConfirmationEmailForm = "_SendConfirmationEmailForm";
                public readonly string _SignOnForm = "_SignOnForm";
                public readonly string _UserGravatarImg = "_UserGravatarImg";
                public readonly string _UserJumbotron = "_UserJumbotron";
                public readonly string _VerifyConfirmEmailSecretForm = "_VerifyConfirmEmailSecretForm";
                public readonly string SignIn = "SignIn";
                public readonly string SignOnCreateRemoteMembership = "SignOnCreateRemoteMembership";
                public readonly string SignOnSendConfirmationEmail = "SignOnSendConfirmationEmail";
                public readonly string SignOnVerifyConfirmEmailSecret = "SignOnVerifyConfirmEmailSecret";
                public readonly string SignUpCreateLocalMembership = "SignUpCreateLocalMembership";
                public readonly string SignUpSendConfirmationEmail = "SignUpSendConfirmationEmail";
                public readonly string SignUpVerifyConfirmEmailSecret = "SignUpVerifyConfirmEmailSecret";
                public readonly string User = "User";
            }
            public readonly string _ChangeUserNameForm = "~/Views/Security/_ChangeUserNameForm.cshtml";
            public readonly string _ConfirmEmailWizardSteps = "~/Views/Security/_ConfirmEmailWizardSteps.cshtml";
            public readonly string _SendConfirmationEmailForm = "~/Views/Security/_SendConfirmationEmailForm.cshtml";
            public readonly string _SignOnForm = "~/Views/Security/_SignOnForm.cshtml";
            public readonly string _UserGravatarImg = "~/Views/Security/_UserGravatarImg.cshtml";
            public readonly string _UserJumbotron = "~/Views/Security/_UserJumbotron.cshtml";
            public readonly string _VerifyConfirmEmailSecretForm = "~/Views/Security/_VerifyConfirmEmailSecretForm.cshtml";
            public readonly string SignIn = "~/Views/Security/SignIn.cshtml";
            public readonly string SignOnCreateRemoteMembership = "~/Views/Security/SignOnCreateRemoteMembership.cshtml";
            public readonly string SignOnSendConfirmationEmail = "~/Views/Security/SignOnSendConfirmationEmail.cshtml";
            public readonly string SignOnVerifyConfirmEmailSecret = "~/Views/Security/SignOnVerifyConfirmEmailSecret.cshtml";
            public readonly string SignUpCreateLocalMembership = "~/Views/Security/SignUpCreateLocalMembership.cshtml";
            public readonly string SignUpSendConfirmationEmail = "~/Views/Security/SignUpSendConfirmationEmail.cshtml";
            public readonly string SignUpVerifyConfirmEmailSecret = "~/Views/Security/SignUpVerifyConfirmEmailSecret.cshtml";
            public readonly string User = "~/Views/Security/User.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
