//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(Tripod.Ioc.EntityFramework.EntityDbContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets3d6bcb17e486b5fa18e5ccb1fd86e39ce1835aa5386e51b6dadef719b832b4cd))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySets3d6bcb17e486b5fa18e5ccb1fd86e39ce1835aa5386e51b6dadef719b832b4cd : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "3d6bcb17e486b5fa18e5ccb1fd86e39ce1835aa5386e51b6dadef719b832b4cd"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.User")
            {
                return GetView0();
            }

            if (extentName == "EntityDbContext.Users")
            {
                return GetView1();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.User.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing User
        [CodeFirstDatabaseSchema.User](T1.User_Id, T1.User_Name)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Name AS User_Name, 
            True AS _from0
        FROM EntityDbContext.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EntityDbContext.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [Tripod.Ioc.EntityFramework.User](T1.User_Id, T1.User_Name)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Name AS User_Name, 
            True AS _from0
        FROM CodeFirstDatabase.User AS T
    ) AS T1");
        }
    }
}
